[package]
name = "logger_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
find-crate = "0.6.3"
itertools = "0.11.0"
proc-macro2 = "1.0.63"
toml = "0.7.6"
